version: "3.9"
services:
  mcserver:
    build:
      context: .
      args:
        # MCSERVER_UID: 1000
        MCSERVER_GID: 1001

    ports:
      - "25565:25565"
    volumes:
      - ${PWD}/eula.txt:/srv/mcserver/eula.txt
      - ${PWD}/server.properties:/srv/mcserver/server.properties
      - ./world:/srv/mcserver/world:rw
      - ./plugins:/srv/mcserver/plugins:rw
